# Generated by Django 4.1.1 on 2022-10-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0002_alter_city_options_advertiser'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertiser',
            name='businesses',
            field=models.ManyToManyField(to='signage.business'),
        ),
    ]
