# Generated by Django 4.1.1 on 2022-12-16 16:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0007_remove_advertiser_ad_type_remove_advertiser_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='pabblysubscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
